name: Scheduled Update
on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '*/30 * * * *'
concurrency: commit
jobs:
  fetch:
    name: Fetch data, and commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Config git user
        run: |
          git config user.name "Russell Smith"
          git config user.email ukd1@users.noreply.github.com
      - name: Hello
        run: |
          echo "Hello, RC!" > HELLO.md
          git add HELLO.md
      - name: Commit, and push repo
        run: |
          git commit -m "Updated data in run ${GITHUB_RUN_NUMBER}" || true
          git push || true
